service: form-sg-slack-bridge
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1

plugins:
  - serverless-plugin-typescript

functions:
  handle-form-sg-callback:
    handler: index.handler
